name: <your-service-name>
env:
  JAVA_OPTS: "-Dserver.port=$PORT $JAVA_OPTS"
build:
  image: 'render.com/images/jvm:17'
  dockerfile: Dockerfile
  environment:
    - DATABASE_URL=jdbc:postgresql://dpg-cgdfv002qv2aq5lksop0-a:5432/honey
    - DATABASE_USER=honey
    - DATABASE_PASSWORD=jcKOYDXEym2wrZ2Vf53f97mwTdHsX9zO
web:
  command: java $JAVA_OPTS -jar app.jar
